### ISSUE TITLE
man 7 signal 

### ISSUE THREAD

**Issue by ghost** [ILUGD/talks#31]
**Abstract**
   This would be a short runthrough on linux signals
        
**Expected Duration**
    30 mins

**Resources**
  http://man7.org/linux/man-pages/man7/signal.7.html

**Comment by manasb** [comment]
I like this idea. It could be extended to cover other important linux/unix tools like sed/awk/grep.

**Comment by sourabhtk37** [comment]
Thanks for the feedback. Sed/awk/grep have already been covered in previous meetup. If you want to see some specific talk in next meetup you can suggest by creating an issue, someone might pick it up. :)

**Comment by manasb** [comment]
@sourabhtk37 Hmm, which talk would that be? I took a quick look through https://github.com/ILUGD/talks/blob/master/talks-log/2017.md and didn't notice it.

:)

**Comment by sourabhtk37** [comment]
Some talks are missing from the logs, maybe you could help us find the missing ones by looking at past meetup schedule in either mailing list/meet-up page/social media  and send a PR, after all it's a volunteered effort. :)

>It may be beneficial to newcomers to unix command-line tools to provide these talks/workshops on a regular basis, what do you think?

Yes, sure. In any community," whoever suggests should volunteer for the same". I encourage you to take the initiative so that there is more interests for the same.

**Comment by sourabhtk37** [comment]
Closing this as user doesn't exist.
